import {
  SiteSettings,
  NavItem,
  RoomCMS,
  ExperienceCMS,
  TestimonialCMS,
  GalleryItemCMS,
  PromotionCMS,
  HomeSection,
  RoomsPageData,
  ExperiencesPageData,
} from "./sanity/types";

export const MOCK_SITE_SETTINGS: SiteSettings = {
  propertyName: "ROYAL PALACE",
  tagline: "A Private Resort Homestay in Varkala, Kerala",
  phone: "+91 98765 43210",
  whatsapp: "+91 98765 43210",
  email: "stay@royalpalacevarkala.com",
  address: "North Cliff Road, Kurakkanni, Varkala, Kerala 695141, India",
  googleMapsUrl: "https://maps.google.com/?q=Varkala+Cliff+Kerala",
  instagramUrl: "https://instagram.com/royalpalacevarkala",
  facebookUrl: "https://facebook.com/royalpalacevarkala",
  defaultSeoTitle: "Royal Palace | Luxury Resort Homestay in Varkala, Kerala",
  defaultSeoDescription:
    "A private boutique resort homestay overlooking the cliff & coast of Varkala, Kerala. Quiet luxury, tropical elegance, cinematic slow living...",
};

export const MOCK_NAVIGATION: NavItem[] = [
  { _key: "nav-1", label: "Overview", url: "/", visible: true, order: 1 },
  { _key: "nav-2", label: "Rooms", url: "/rooms", visible: true, order: 2 },
  { _key: "nav-3", label: "Experiences", url: "/experiences", visible: true, order: 3 },
  { _key: "nav-4", label: "Gallery", url: "/gallery", visible: true, order: 4 },
  { _key: "nav-5", label: "About", url: "/about", visible: true, order: 5 },
  { _key: "nav-6", label: "Contact", url: "/contact", visible: true, order: 6 },
];

export const MOCK_ROOMS: RoomCMS[] = [
  {
    _id: "room-1",
    name: "Royal Cliff Suite",
    slug: { current: "royal-cliff-suite" },
    shortDescription: "Panoramic Arabian ocean views, private teak balcony, plunge pool, and bespoke luxury interiors.",
    description:
      "Perched high on the cliffside, the Royal Cliff Suite is our flagship private sanctuary. Featuring hand-carved Malabar teak woodwork, high timber ceilings, an expansive oceanfront private balcony, and an intimate plunge pool overlooking the Arabian Sea.",
    featured: true,
    heroImage: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80",
    ],
    capacity: 2,
    beds: "1 King Suite Bed",
    bathrooms: "1 Ensuite Open-Air Bath",
    amenities: [
      "Arabian Ocean Balcony",
      "Private Plunge Pool",
      "Organic Malabar Teak Furnishings",
      "Handcrafted Kerala Coffee & Tea Bar",
      "Rainfall Shower & Freestanding Tub",
      "High Speed Wi-Fi",
      "Butler Service",
    ],
    highlights: ["Sunset ocean view", "Plunge pool", "King suite"],
    basePrice: 14500,
    ctaLabel: "Reserve Suite",
  },
  {
    _id: "room-2",
    name: "Heritage Teak Villa",
    slug: { current: "heritage-heritage-villa" },
    shortDescription: "A two-bedroom traditional Kerala wooden villa surrounded by lush coconut groves and secret courtyards.",
    description:
      "Inspired by traditional Kerala Tharavadu architecture, this standalone villa combines hundred-year-old carved teak elements with contemporary high-end luxury. Perfect for families or small groups seeking absolute privacy.",
    featured: true,
    heroImage: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80",
    ],
    capacity: 4,
    beds: "2 King Bedrooms",
    bathrooms: "2 Ensuite Bathrooms",
    amenities: [
      "Private Tropical Courtyard",
      "Outdoor Open-Sky Rain Shower",
      "Spacious Veranda & Daybed",
      "In-Villa Dining Setup",
      "Organic Linen & Bathrobes",
    ],
    highlights: ["Two private bedrooms", "Open sky rain shower", "Garden courtyard"],
    basePrice: 22000,
    ctaLabel: "Reserve Villa",
  },
  {
    _id: "room-3",
    name: "Palace Garden Sanctuary",
    slug: { current: "palace-garden-room" },
    shortDescription: "Serene garden-level room immersed in tropical greenery with private sun-dappled veranda.",
    description:
      "Tucked within our private botanical gardens, the Palace Garden Sanctuary offers a quiet retreat sheltered by coconut palms and frangipani blossoms. Wake up to soft birdsong and cool ocean breezes.",
    featured: true,
    heroImage: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80",
    ],
    capacity: 2,
    beds: "1 Queen Bed",
    bathrooms: "1 Luxury Bathroom",
    amenities: [
      "Private Garden Veranda",
      "Lush Palm Views",
      "Artisanal Coffee Brewer",
      "Custom Natural Bath Products",
    ],
    highlights: ["Garden terrace", "Quiet location", "Artisanal breakfast"],
    basePrice: 9800,
    ctaLabel: "Reserve Sanctuary",
  },
];

export const MOCK_EXPERIENCES: ExperienceCMS[] = [
  {
    _id: "exp-1",
    title: "Varkala Cliff Sunset & Mineral Springs",
    slug: { current: "varkala-cliff-sunset" },
    category: "Coastal",
    shortDescription: "Guided golden hour walk along the dramatic red cliffs of Varkala down to the natural freshwater spring.",
    description:
      "Experience the legendary golden hour of Varkala. Walk along the edge of towering red clay cliffs carved by the Arabian Sea, down to the sacred Papanasam mineral springs where natural freshwater trickles straight from the rock into the ocean waves.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80",
    ],
    duration: "2.5 Hours",
    location: "Varkala North Cliff",
    featured: true,
    ctaText: "Book Sunset Walk",
  },
  {
    _id: "exp-2",
    title: "Edava Paravur Kayaking & Backwater Trail",
    slug: { current: "edava-backwater-kayaking" },
    category: "Adventure",
    shortDescription: "Glide silently through tranquil backwaters, mangrove tunnels, and quiet coconut palm canals.",
    description:
      "Paddle through the serene backwater lakes of Edava and Kappil where fresh water meets the sea. Witness traditional canoe fishermen, blue kingfishers, and peaceful water lilies in absolute morning calm.",
    heroImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
    ],
    duration: "3 Hours",
    location: "Edava Backwaters (10 mins away)",
    featured: true,
    ctaText: "Book Kayak Tour",
  },
  {
    _id: "exp-3",
    title: "Authentic Malabar Culinary Tasting",
    slug: { current: "malabar-culinary-tasting" },
    category: "Dining",
    shortDescription: "Private chef dining featuring fresh ocean catch, banana leaf meals, and Kerala coconut curries.",
    description:
      "A curated epicurean journey through Kerala's famous spice coast. Prepared daily using fresh fish bought directly from local fishermen at dawn and organic spices grown in nearby hill estates.",
    heroImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
    ],
    duration: "2 Hours",
    location: "Royal Palace Private Veranda",
    featured: true,
    ctaText: "Reserve Culinary Experience",
  },
];

export const MOCK_TESTIMONIALS: TestimonialCMS[] = [
  {
    _id: "test-1",
    quote:
      "Royal Palace is unlike any hotel in Kerala. It feels like staying in a friend's architectural luxury villa. The ocean views from the cliff suite sunset were breathtaking.",
    guestName: "Alexander & Sophia Richter",
    guestLocation: "Zurich, Switzerland",
    source: "Direct Guest",
    featured: true,
    order: 1,
  },
  {
    _id: "test-2",
    quote:
      "The quietness, the smell of teak wood, the private backwater kayaking in the morning... Royal Palace delivered the calmest 4 days of our lives.",
    guestName: "Arjun & Divya Nair",
    guestLocation: "Bengaluru, India",
    source: "TripAdvisor",
    featured: true,
    order: 2,
  },
];

export const MOCK_GALLERY: GalleryItemCMS[] = [
  {
    _id: "gal-1",
    title: "Cliffside Ocean Sunset",
    media: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    type: "image",
    category: "Varkala",
    featured: true,
    size: "large",
  },
  {
    _id: "gal-2",
    title: "Teak Suite Veranda",
    media: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    type: "image",
    category: "Rooms",
    featured: true,
    size: "standard",
  },
  {
    _id: "gal-3",
    title: "Tropical Garden Pathway",
    media: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80",
    type: "image",
    category: "Architectural",
    featured: true,
    size: "tall",
  },
  {
    _id: "gal-4",
    title: "Backwater Kayaking",
    media: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
    type: "image",
    category: "Slow Living",
    featured: true,
    size: "wide",
  },
];

export const MOCK_PROMOTION: PromotionCMS = {
  _id: "prom-1",
  title: "Monsoon & Winter Coastal Escape",
  description: "Book 3 nights or more at Royal Palace and receive complimentary sunrise kayaking and private coastal seafood dinner.",
  ctaLabel: "Claim Escape Package",
  ctaUrl: "/booking",
  validFrom: "2026-06-01",
  validUntil: "2027-03-31",
  enabled: true,
};

export const MOCK_HOME_SECTIONS: HomeSection[] = [
  {
    _key: "sec-hero",
    _type: "heroSection",
    enabled: true,
    order: 1,
    eyebrow: "PRIVATE RESORT HOMESTAY • VARKALA, KERALA",
    heading: "A Private Stay Overlooking the Arabian Sea",
    subtitle: "More than a stay — the starting point for an authentic Varkala slow living experience.",
    desktopVideo: "https://assets.mixkit.co/videos/preview/mixkit-waves-coming-to-the-beach-5016-large.mp4",
    posterImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1920&q=80",
    primaryCtaText: "CHECK AVAILABILITY",
    secondaryCtaText: "DISCOVER THE STAY",
  },
  {
    _key: "sec-booking-bar",
    _type: "bookingBarSection",
    enabled: true,
    order: 2,
  },
  {
    _key: "sec-editorial",
    _type: "editorialSection",
    enabled: true,
    order: 3,
    eyebrow: "SLOW HOSPITALITY IN KERALA",
    title: "MORE THAN A STAY. A SLOWER WAY TO EXPERIENCE VARKALA.",
    bodyParagraphs: [
      "Set atop the iconic cliffs of Varkala where ancient red earth meets the deep blue Arabian ocean, Royal Palace is a private boutique sanctuary crafted for thoughtful travelers.",
      "Here, days unfold with intention: soft sea air blowing through teak shutters, fresh coconut water served on sunlit verandas, and quiet evenings watching the sun dip into the horizon.",
    ],
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    imageCaption: "Royal Cliff Suite Veranda overlooking Varkala Coast",
    quote: "Quiet luxury born from Kerala wood, sea salt, and unhurried time.",
  },
  {
    _key: "sec-rooms",
    _type: "roomShowcaseSection",
    enabled: true,
    order: 4,
    eyebrow: "PRIVATE ACCOMMODATION",
    title: "Bespoke Suites & Teak Villas",
    subtitle: "Intimate rooms engineered for privacy, natural light, and architectural stillness.",
  },
  {
    _key: "sec-story",
    _type: "storyScrollerSection",
    enabled: true,
    order: 5,
    eyebrow: "THE CINEMATIC JOURNEY",
    title: "A Day in Varkala",
    scenes: [
      {
        _key: "sc-1",
        title: "MORNING COFFEE",
        subtitle: "07:00 AM • THE VERANDA",
        description: "Freshly ground South Indian filter coffee served in warm clay pots as morning mist clears off the palm canopy.",
        media: "https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=1200&q=80",
        mediaType: "image",
      },
      {
        _key: "sc-2",
        title: "YOUR PRIVATE SUITE",
        subtitle: "10:00 AM • ARCHITECTURAL STILLNESS",
        description: "High ceilings, natural linen, and hand-carved teak wood bathed in soft coastal illumination.",
        media: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
        mediaType: "image",
      },
      {
        _key: "sc-3",
        title: "BACKWATER KAYAKING",
        subtitle: "03:30 PM • EDAVA LAGOON",
        description: "Glide under palm tree arches along silent backwaters where river waters flow gently into the sea.",
        media: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
        mediaType: "image",
      },
      {
        _key: "sc-4",
        title: "CLIFFSIDE GOLDEN HOUR",
        subtitle: "05:45 PM • VARKALA CLIFF",
        description: "Watch the red cliffs turn deep crimson while fishermen bring in evening nets against a violet sky.",
        media: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
        mediaType: "image",
      },
    ],
  },
  {
    _key: "sec-exp",
    _type: "experienceGridSection",
    enabled: true,
    order: 6,
    eyebrow: "CURATED EXPERIENCES",
    title: "Explore Varkala Coast",
    subtitle: "Immerse in the nature, culture, and coastal life of Southern Kerala.",
  },
  {
    _key: "sec-timeline",
    _type: "dayTimelineSection",
    enabled: true,
    order: 7,
    eyebrow: "DAILY RHYTHM",
    title: "A Day at Royal Palace",
    subtitle: "An unhurried itinerary designed for restful living.",
    items: [
      {
        _key: "t-1",
        time: "07:00 AM",
        title: "Dawn Filter Coffee",
        description: "Served on your private veranda with fresh papaya and roasted cardamoms.",
      },
      {
        _key: "t-2",
        time: "09:00 AM",
        title: "Kerala Slow Breakfast",
        description: "Steamed appams, coconut stew, and fresh tropical fruit juices.",
      },
      {
        _key: "t-3",
        time: "11:30 AM",
        title: "Cliff & Beach Exploration",
        description: "Walk down the cliff pathway to Papanasam beach and natural rock springs.",
      },
      {
        _key: "t-4",
        time: "03:30 PM",
        title: "Ayurvedic Herbal Bath or Kayaking",
        description: "Restore with traditional Kerala herbal oils or paddle backwater channels.",
      },
      {
        _key: "t-5",
        time: "05:45 PM",
        title: "Golden Hour Ocean View",
        description: "Sunset drinks on the cliff lounge listening to ocean waves.",
      },
      {
        _key: "t-6",
        time: "08:00 PM",
        title: "Private Seafood Dinner",
        description: "Fresh ocean catch marinated in coastal spices served under palm candlelight.",
      },
    ],
  },
  {
    _key: "sec-gallery",
    _type: "gallerySection",
    enabled: true,
    order: 8,
    eyebrow: "VISUAL JOURNAL",
    title: "Atmosphere & Moments",
    subtitle: "Snapshots of architecture, ocean sunlight, and slow living.",
  },
  {
    _key: "sec-testimonials",
    _type: "testimonialsSection",
    enabled: true,
    order: 9,
    eyebrow: "GUEST REVIEWS",
    title: "Guest Stories",
  },
  {
    _key: "sec-location",
    _type: "locationSection",
    enabled: true,
    order: 10,
    eyebrow: "LOCATION & SURROUNDINGS",
    title: "Close to Everything. Away from the Noise.",
    description: "Royal Palace is positioned on North Cliff in Varkala, offering walking access to the beach and cliffside cafes while keeping total acoustic privacy.",
    address: "North Cliff Road, Kurakkanni, Varkala, Kerala 695141, India",
    mapUrl: "https://maps.google.com/?q=Varkala+Cliff+Kerala",
    landmarks: [
      { name: "Papanasam Beach & Cliff", distance: "4 mins walk", description: "Main red clay cliff promenade and ocean beach." },
      { name: "Edava Backwater Lake", distance: "10 mins drive", description: "Tranquil lagoon for kayaking and boat rides." },
      { name: "Varkala Railway Station", distance: "12 mins drive", description: "Direct express train connectivity across South India." },
      { name: "Trivandrum International Airport (TRV)", distance: "50 mins drive", description: "Nearest international airport with airport pickup available." },
    ],
  },
  {
    _key: "sec-promotion",
    _type: "promotionSection",
    enabled: true,
    order: 11,
    promotionRef: MOCK_PROMOTION,
  },
  {
    _key: "sec-final-cta",
    _type: "finalCtaSection",
    enabled: true,
    order: 12,
    eyebrow: "YOUR VARKALA STORY BEGINS HERE",
    heading: "Experience Quiet Luxury on the Kerala Coast",
    subtitle: "Reserve your private suite or villa at Royal Palace Varkala.",
    buttonText: "CHECK AVAILABILITY",
    backgroundImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1920&q=80",
  },
];

export const MOCK_ROOMS_PAGE: RoomsPageData = {
  eyebrow: "ACCOMMODATIONS & SUITES",
  heading: "Architectural Sanctuaries",
  subtitle:
    "Each suite and villa at Royal Palace is crafted from warm Kerala teak, natural stone, and expansive ocean balconies designed to capture slow coastal daylight.",
  seoTitle: "Accommodations & Suites | Royal Palace",
  seoDescription:
    "Discover luxury cliffside suites and heritage teak villas at Royal Palace Varkala.",
  bookCtaText: "Book This Room",
  detailsCtaText: "View Details",
  amenitiesHeading: "Key Amenities",
};

export const MOCK_EXPERIENCES_PAGE: ExperiencesPageData = {
  eyebrow: "CURATED EXPERIENCES",
  heading: "Discover Varkala & Beyond",
  subtitle:
    "From dawn backwater kayaking to cliffside golden hour walks, we curate quiet, authentic journeys into Southern Kerala’s coastal culture.",
  detailsCtaText: "Explore Journey",
  seoTitle: "Varkala Experiences | Royal Palace",
  seoDescription:
    "Explore cliffside walks, backwater kayaking, and authentic Malabar dining at Royal Palace Varkala.",
};
